# Generated by Django 5.1.4 on 2025-01-13 11:26

from django.db import migrations, models

import houses.models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housephoto",
            name="photo",
            field=models.ImageField(
                upload_to=houses.models.house_photo_upload_path,
                verbose_name="Фотография",
            ),
        ),
    ]
