# Generated by Django 5.1.4 on 2025-01-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_alter_housephoto_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeaderSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Заголовок в header снизу"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=250, verbose_name="Описание в header снизу"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeaderText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Меняющийся текст в hedaer"
                    ),
                ),
            ],
        ),
    ]
