# Generated by Django 5.1.4 on 2025-01-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_alter_house_description_alter_news_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
