# Generated by Django 5.1.4 on 2025-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_headersection_headertext"),
    ]

    operations = [
        migrations.AddField(
            model_name="headertext",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Начальный текст"),
        ),
    ]
