# Generated by Django 5.1.4 on 2025-01-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_headertext_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Название раздела"),
                ),
                (
                    "description",
                    models.TextField(max_length=250, verbose_name="Описание раздела"),
                ),
            ],
            options={
                "verbose_name": "Раздел О нас",
                "verbose_name_plural": "Разделы О нас",
            },
        ),
        migrations.AlterModelOptions(
            name="headersection",
            options={"verbose_name": "Текст внизу header"},
        ),
        migrations.AlterModelOptions(
            name="headertext",
            options={"verbose_name": "Меняющийся текст в header"},
        ),
        migrations.AlterModelOptions(
            name="house",
            options={"verbose_name": "Дом", "verbose_name_plural": "Дома"},
        ),
        migrations.AlterModelOptions(
            name="housesection",
            options={
                "verbose_name": "Раздел Дома",
                "verbose_name_plural": "Разделы Дома",
            },
        ),
        migrations.AlterField(
            model_name="headertext",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Активный (начальный) текст"
            ),
        ),
        migrations.AlterField(
            model_name="housesection",
            name="description",
            field=models.TextField(max_length=250, verbose_name="Описание раздела"),
        ),
    ]
