# Generated by Django 5.1.4 on 2025-01-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0005_aboutsection_alter_headersection_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="housephoto",
            options={"verbose_name": "Фото домов", "verbose_name_plural": "Фото домов"},
        ),
    ]
