# Generated by Django 5.1.4 on 2025-01-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0006_alter_housephoto_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutsection",
            name="description",
            field=models.TextField(verbose_name="Описание раздела"),
        ),
        migrations.AlterField(
            model_name="housesection",
            name="description",
            field=models.TextField(verbose_name="Описание раздела"),
        ),
    ]
