# Generated by Django 5.1.4 on 2025-01-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0007_alter_aboutsection_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutSection",
        ),
        migrations.DeleteModel(
            name="HeaderSection",
        ),
        migrations.RemoveField(
            model_name="house",
            name="section",
        ),
        migrations.DeleteModel(
            name="HouseSection",
        ),
    ]
