# Generated by Django 5.1.4 on 2025-01-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0008_delete_aboutsection_delete_headersection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="style",
        ),
    ]
