# Generated by Django 5.1.4 on 2025-01-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0009_remove_house_style"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="headertext",
            options={
                "verbose_name": "Текст в header",
                "verbose_name_plural": "Тексты в header",
            },
        ),
    ]
