# Generated by Django 5.1.4 on 2025-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0010_alter_headertext_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Адрес")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Адрес почты",
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Telegram"
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на WhatsApp"
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Instagram"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактная информация",
            },
        ),
        migrations.AlterField(
            model_name="headertext",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Текст"),
        ),
    ]
